#!/bin/sh

##################################################
#  ____ ____  ______        ____  __ ____   ____
# | __ ) ___||  _ \ \      / /  \/  |  _ \ / ___|
# |  _ \___ \| |_) \ \ /\ / /| |\/| | |_) | |
# | |_) |__) |  __/ \ V  V / | |  | |  _ <| |___
# |____/____/|_|     \_/\_/  |_|  |_|_| \_\\____|
##################################################

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor setup (one screen for now)
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Gaps and border size
bspc config border_width         3
bspc config window_gap           6
bspc config top_padding          4
bspc config bottom_padding       4
bspc config left_padding         4
bspc config right_padding        4

# Colors
bspc config normal_border_color   "#190101"
bspc config focused_border_color  "#ff914d"
bspc config active_border_color   "#ffbe76"
bspc config urgent_border_color   "#ffbe76"

# Focus behavior
bspc config focus_follows_pointer  false
bspc config pointer_follows_focus  true

# Split ratio
bspc config split_ratio           0.52

# Polybar
$HOME/.config/polybar/launch.sh &

